spring:
  application:
    name: security
  datasource:
    url:  jdbc:mysql://localhost:3306/demo
    username: root
    password: Sudharsan@24
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform:  org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true